name: Slideshow
main: com.github.krockode.slideshow.Slideshow
version: ${project.version}
author: krockode
description: Slideshow.
commands:
   slides:
      description: |
                Create slideshows of your world
      usage: /slides [create|add|save|run] [slideshowname]
# /slides create [slideshowname]
#   creates a new slideshow
# /slides add
#   adds the current location to the slideshow
#   (must have already run create)
# /slides save
#   saves the current slideshow
# /slides run [slideshowname] [period]
#   runs the previously saved slideshow named slideshowname
# /slides stop
#   stop the currently running slideshow
# /slides next
#   debug option to cycle through slideshow manually
